In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['log_loss', 'gini', 'entropy'],
            'max_features':['auto','sqrt','log2'],
            'splitter':['best','random']}

grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
grid=grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END criterion=log_loss, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=log_loss, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=log_loss, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=log_loss, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=log_loss, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=log_loss, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=log_loss, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=log_loss, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=log_loss, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=log_loss, max_features=auto, splitt

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\

In [17]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.000742      0.000433         0.000000        0.000000   
1        0.000066      0.000133         0.000000        0.000000   
2        0.001407      0.000805         0.005065        0.002139   
3        0.000799      0.000748         0.005753        0.004478   
4        0.001598      0.000489         0.004177        0.000347   
5        0.001398      0.000490         0.004117        0.000278   
6        0.000000      0.000000         0.000000        0.000000   
7        0.000000      0.000000         0.000000        0.000000   
8        0.000000      0.000000         0.003133        0.006266   
9        0.000000      0.000000         0.006251        0.007656   
10       0.001623      0.002774         0.004348        0.005850   
11       0.000999      0.000633         0.005416        0.002826   
12       0.000199      0.000398         0.000000        0.000000   
13       0.000608      0.000496         0.000000        0.000000   
14       0.001273      0.000389         0.004061        0.000100   
15       0.000799      0.000400         0.002988        0.001608   
16       0.000000      0.000000         0.006240        0.007642   
17       0.000000      0.000000         0.003125        0.006250   

   param_criterion param_max_features param_splitter  \
0         log_loss               auto           best   
1         log_loss               auto         random   
2         log_loss               sqrt           best   
3         log_loss               sqrt         random   
4         log_loss               log2           best   
5         log_loss               log2         random   
6             gini               auto           best   
7             gini               auto         random   
8             gini               sqrt           best   
9             gini               sqrt         random   
10            gini               log2           best   
11            gini               log2         random   
12         entropy               auto           best   
13         entropy               auto         random   
14         entropy               sqrt           best   
15         entropy               sqrt         random   
16         entropy               log2           best   
17         entropy               log2         random   

                                               params  split0_test_score  \
0   {'criterion': 'log_loss', 'max_features': 'aut...                NaN   
1   {'criterion': 'log_loss', 'max_features': 'aut...                NaN   
2   {'criterion': 'log_loss', 'max_features': 'sqr...           0.964286   
3   {'criterion': 'log_loss', 'max_features': 'sqr...           0.964286   
4   {'criterion': 'log_loss', 'max_features': 'log...           0.929144   
5   {'criterion': 'log_loss', 'max_features': 'log...           0.964572   
6   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
7   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
8   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.982051   
9   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.982221   
10  {'criterion': 'gini', 'max_features': 'log2', ...           0.982221   
11  {'criterion': 'gini', 'max_features': 'log2', ...           0.947015   
12  {'criterion': 'entropy', 'max_features': 'auto...                NaN   
13  {'criterion': 'entropy', 'max_features': 'auto...                NaN   
14  {'criterion': 'entropy', 'max_features': 'sqrt...           0.946663   
15  {'criterion': 'entropy', 'max_features': 'sqrt...           0.982221   
16  {'criterion': 'entropy', 'max_features': 'log2...           0.929513   
17  {'criterion': 'entropy', 'max_features': 'log2...           0.982221   

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN   
1                 NaN                NaN                NaN   
2           

In [18]:
grid_pred=grid.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
cm

array([[45,  0],
       [ 3, 72]])

In [20]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120



In [21]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_pred,average='weighted')
f1_macro

0.9751481237656352

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.98)

In [23]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [32]:
inpt=sc.transform([[2, 76.45994832, 3, 0, 148, 57, 3, 137, 4.6, 12.51, 38,8408, 4.7, 0, 1, 0, 0, 1, 0,0, 0, 0, 0, 0,1, 1, 0]])
#results=grid.predict([[2, 76.45994832, 3, 0, 148, 57, 3, 137, 4.6, 12.51, 38,8408, 4.7, 0, 1, 0, 0, 1, 0,0, 0, 0, 0, 0,1, 1, 0]])
results=grid.predict(inpt)
results

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1])

In [25]:
inpt1=sc.transform([[15,80, 0, 0, 93, 17, 1, 136, 3, 16, 50,
       6200, 5.2, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0,
       1, 0, 0]])
results1=grid.predict(inpt1)
results1

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

In [26]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [27]:
def res():
    if (results1==1):
        print("The person has Kidney disease.")
    else:
        print("The person does not have kidney disease.")
        
res()

The person does not have kidney disease.


In [28]:
results

array([1])