In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import GridSearchCV
param_grid={'penalty':['l1','l2','elasticnet','none'],
            'C':[0.1,0.5,0.10,0.50,1],
            'random_state':[0]}

grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
grid=grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END ...C=0.1, penalty=l1, random_state=0;, score=nan total time=   0.0s
[CV 2/5] END ...C=0.1, penalty=l1, random_state=0;, score=nan total time=   0.0s
[CV 3/5] END ...C=0.1, penalty=l1, random_state=0;, score=nan total time=   0.0s
[CV 4/5] END ...C=0.1, penalty=l1, random_state=0;, score=nan total time=   0.0s
[CV 5/5] END ...C=0.1, penalty=l1, random_state=0;, score=nan total time=   0.0s
[CV 1/5] END .C=0.1, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 2/5] END .C=0.1, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 3/5] END .C=0.1, penalty=l2, random_state=0;, score=0.947 total time=   0.0s
[CV 4/5] END .C=0.1, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 5/5] END .C=0.1, penalty=l2, random_state=0;, score=0.982 total time=   0.0s
[CV 1/5] END C=0.1, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, penalty=elasticnet, ra

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

[CV 2/5] END .C=0.5, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 3/5] END .C=0.5, penalty=l2, random_state=0;, score=0.964 total time=   0.0s
[CV 4/5] END .C=0.5, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 5/5] END .C=0.5, penalty=l2, random_state=0;, score=1.000 total time=   0.0s
[CV 1/5] END C=0.5, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, penalty=elasticnet, random_state=0;, score=nan total time=   0.0s
[CV 1/5] END .C=0.5, penalty=none, random_state=0;, score=nan total time=   0.0s
[CV 2/5] END .C=0.5, penalty=none, random_state=0;, score=nan total time=   0.0s
[CV 3/5] END .C=0.5, penalty=none, random_state=0;, score=nan total time=   0.0s
[CV

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [11]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.000828      0.000414         0.000000        0.000000      0.1   
1        0.004561      0.000417         0.004906        0.000543      0.1   
2        0.000000      0.000000         0.000000        0.000000      0.1   
3        0.000000      0.000000         0.000000        0.000000      0.1   
4        0.000801      0.000400         0.000000        0.000000      0.5   
5        0.004829      0.005694         0.003925        0.006055      0.5   
6        0.000000      0.000000         0.000000        0.000000      0.5   
7        0.000000      0.000000         0.000000        0.000000      0.5   
8        0.003125      0.006250         0.000000        0.000000      0.1   
9        0.000000      0.000000         0.006250        0.007655      0.1   
10       0.003131      0.006261         0.000000        0.000000      0.1   
11       0.000000      0.000000         0.000000        0.000000      0.1   
12       0.000000      0.000000         0.000000        0.000000      0.5   
13       0.008305      0.004219         0.003780        0.001775      0.5   
14       0.000000      0.000000         0.000000        0.000000      0.5   
15       0.000600      0.000490         0.000000        0.000000      0.5   
16       0.000554      0.000470         0.000000        0.000000      1.0   
17       0.005131      0.005728         0.004220        0.005924      1.0   
18       0.000000      0.000000         0.000000        0.000000      1.0   
19       0.000000      0.000000         0.000000        0.000000      1.0   

   param_penalty  param_random_state  \
0             l1                   0   
1             l2                   0   
2     elasticnet                   0   
3           none                   0   
4             l1                   0   
5             l2                   0   
6     elasticnet                   0   
7           none                   0   
8             l1                   0   
9             l2                   0   
10    elasticnet                   0   
11          none                   0   
12            l1                   0   
13            l2                   0   
14    elasticnet                   0   
15          none                   0   
16            l1                   0   
17            l2                   0   
18    elasticnet                   0   
19          none                   0   

                                               params  split0_test_score  \
0      {'C': 0.1, 'penalty': 'l1', 'random_state': 0}                NaN   
1      {'C': 0.1, 'penalty': 'l2', 'random_state': 0}           1.000000   
2   {'C': 0.1, 'penalty': 'elasticnet', 'random_st...                NaN   
3    {'C': 0.1, 'penalty': 'none', 'random_state': 0}                NaN   
4      {'C': 0.5, 'penalty': 'l1', 'random_state': 0}                NaN   
5      {'C': 0.5, 'penalty': 'l2', 'random_state': 0}           0.982221   
6   {'C': 0.5, 'penalty': 'elasticnet', 'random_st...                NaN   
7    {'C': 0.5, 'penalty': 'none', 'random_state': 0}                NaN   
8      {'C': 0.1, 'penalty': 'l1', 'random_state': 0}                NaN   
9      {'C': 0.1, 'penalty': 'l2', 'random_state': 0}           1.000000   
10  {'C': 0.1, 'penalty': 'elasticnet', 'random_st...                NaN   
11   {'C': 0.1, 'penalty': 'none', 'random_state': 0}                NaN   
12     {'C': 0.5, 'penalty': 'l1', 'random_state': 0}                NaN   
13     {'C': 0.5, 'penalty': 'l2', 'random_state': 0}           0.982221   
14  {'C': 0.5, 'penalty': 'elasticnet', 'random_st...                NaN   
15   {'C': 0.5, 'penalty': 'none', 'random_state': 0}                NaN   
16       {'C': 1, 'penalty': 'l1', 'random_state': 0}                NaN   
17       {'C': 1, 'penalty': 'l2', 'random_state': 0}           0.982221   
18  {'C': 1, 'penalty': 'elasticnet', 'random_stat...                NaN   
19     {'C': 1, 'penalty'

In [12]:
grid_pred=grid.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
cm

array([[45,  0],
       [ 1, 74]])

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_pred,average='weighted')
f1_macro

0.9916844900066377

In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(1.0)

In [17]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [18]:
inpt=sc.transform([[2, 76.45994832, 3, 0, 148, 57, 3, 137, 4.6, 12.51, 38,8408, 4.7, 0, 1, 0, 0, 1, 0,0, 0, 0, 0, 0,1, 1, 0]])
#results=grid.predict([[2, 76.45994832, 3, 0, 148, 57, 3, 137, 4.6, 12.51, 38,8408, 4.7, 0, 1, 0, 0, 1, 0,0, 0, 0, 0, 0,1, 1, 0]])
results=grid.predict(inpt)
results

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1])

In [19]:
inpt1=sc.transform([[15,80, 0, 0, 93, 17, 1, 136, 3, 16, 50,
       6200, 5.2, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0,
       1, 0, 0]])
results1=grid.predict(inpt1)
results1

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

In [26]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [20]:
def res():
    if (results1==1):
        print("The person has Kidney disease.")
    else:
        print("The person does not have kidney disease.")
        
res()

The person does not have kidney disease.


In [21]:
results1

array([0])